### ISSUE TITLE
Windows 10 on ARM64 support

### ISSUE THREAD

**Issue by sidd-kishan** [OSRDrivers/WDF-I#1]
Please let us know when can we have an ARM64 version for Windows on ARM OS. As it will encourage the development of drivers on Windows on ARM platform.

**Comment by PeterGV** [comment]
Are you looking for ARM versions for any specific project?

It should be a simple matter to add an ARM64 target to any of the solutions.  Remember, Windows drivers are only rarely changed or conditionalized based on target architecture.  So there **should** be no source-code changes needed for any of these projects to support ARM64.
